name: MyPy check
on: [push]
jobs:
  django4:
    name: Django-4
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Set up Python 3.8.5
      uses: actions/setup-python@v2
      with:
        python-version: 3.8.5
    - name: Restore pip cache
      uses: actions/cache@v1
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Use local settings
      run: cp mysite/local_settings.py.ci mysite/local_settings.py
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install mypy django-stubs==1.4.0
    - name: Mypy tests
      run: |
        export DIFF_FILES=$(git diff --name-only --diff-filter=ACM $(git merge-base HEAD origin/master) | grep "\.py" | grep -v "settings" | grep -v "migrations")
        if [[ ! -z $DIFF_FILES ]]
        then
          echo "[MYPY] Checking ..." $DIFF_FILES
          mypy $DIFF_FILES --ignore-missing-imports --disallow-untyped-defs --follow-imports silent
        fi
